config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'login' => 'user_sessions#signin'
  post 'login' => 'user_sessions#authenticate'
  get 'logout' => 'user_sessions#signout'

  resources :users do
    collection do
      get 'list'
    end
  end

  resources :books do
    collection do
      get 'list'
    end
    put 'borrow'
    resources :details, controller: 'book/details'
  end

  resources :borroweds, except: [:index, :new, :edit, :show, :create, :update, :destroy] do
    get 'return_book'
  end

  namespace :api do
    namespace :v1 do
      post 'login' => 'user_sessions#authenticate'
      get 'dashboard' => 'dashboards#index'
      resources :users, only: [:index, :show, :create, :update, :destroy]
      resources :books, only: [:index, :show, :create, :update, :destroy] do
        collection do
          get 'search'
        end
        put 'borrow'
        resources :details, only: [:show, :create, :update, :destroy], controller: 'book/details'
      end
      resources :borroweds, only: :index do
        patch 'return_book'
      end
    end
  end


  # Defines the root path route ("/"),
  root "books#index"
end

app/views/shared/_flash.html.erb
<div class="alert <%= flash_class_for(msg_type) %>">
  <div class="container">
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= message %>
  </div>
</div>

app/views/shared/_menu.html.erb
<div class="col-sm-auto bg-light sticky-top">
  <div class="d-flex flex-sm-column flex-row flex-nowrap bg-light align-items-center sticky-top">
      <a href="/" class="d-block p-3 link-dark text-decoration-none" title="" data-bs-toggle="tooltip" data-bs-placement="right">
          <h2>LB</h2>
      </a>
      <ul class="nav nav-pills nav-flush flex-sm-column flex-row flex-nowrap mb-auto mx-auto text-center align-items-center">
        <% if current_user.librarian? %>
            <li class="nav-item">
                <a href=<%= users_path %> class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Home">
                    <i class="bi-people fs-1"></i>
                </a>
            </li>
        <% end %>
        <li class="nav-item">
            <a href=<%= books_path %> class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Home">
                <i class="bi-book fs-1"></i>
            </a>
        </li>
      </ul>
      <div class="dropdown">
          <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi-person-circle h2"></i>
          </a>
          <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
              <li><a class="dropdown-item" href=<%= user_path(@current_user) %>>My Profile</a></li>
              <li><a class="dropdown-item" href=<%= logout_path %>>Logout</a></li>
          </ul>
      </div>
  </div>
</div>

app/views/shared/_notices.html.erb
<div id="flash">
  <% flash.each do |msg_type, message| %>
    <%= render partial: "shared/flash", locals: { msg_type: msg_type, message: message } %>
  <% end %>
</div>

app/views/shared/_pagination.html.erb
<div class="row">
  <div class="col-12">
    <div class="d-flex justify-content-center">
      <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>
</div>