config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'login' => 'user_sessions#signin'
  post 'login' => 'user_sessions#authenticate'
  get 'logout' => 'user_sessions#signout'

  resources :users do
    collection do
      get 'list'
    end
  end

  resources :books do
    collection do
      get 'list'
    end
    put 'borrow'
    resources :details, controller: 'book/details'
  end

  resources :borroweds, except: [:index, :new, :edit, :show, :create, :update, :destroy] do
    get 'return_book'
  end

  namespace :api do
    namespace :v1 do
      post 'login' => 'user_sessions#authenticate'
      get 'dashboard' => 'dashboards#index'
      resources :users, only: [:index, :show, :create, :update, :destroy]
      resources :books, only: [:index, :show, :create, :update, :destroy] do
        collection do
          get 'search'
        end
        put 'borrow'
        resources :details, only: [:show, :create, :update, :destroy], controller: 'book/details'
      end
      resources :borroweds, only: :index do
        patch 'return_book'
      end
    end
  end


  # Defines the root path route ("/"),
  root "books#index"
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_many :details
  has_many :borroweds

  validates :title, :isbn, :copies, presence: true
  validates :isbn, uniqueness: true

  scope :search, lambda { |query|
    left_joins(:details)
      .where('books.title LIKE ? OR books.isbn LIKE ? OR book_details.description LIKE ?', "%#{query}%", "%#{query}%", "%#{query}%")
      .distinct(:id)
  }

  def self.total_books
    Book.sum(:copies)
  end

  def self.never_borrowed
    Borrowed.where(book_id: Book.all.pluck(:id)).distinct(:book_id)
  end

  def authors
    details.where(name: :author).order(:description).pluck(:description)
  end

  def genres
    details.where(name: :genre).order(:description).pluck(:description)
  end

  def publishers
    details.where(name: :publisher).order(:description).pluck(:description)
  end

  def available?
    borroweds.not_returned.count < copies
  end

  def already_borrowed_by_this_user?(user)
    borroweds.not_returned.where(user_id: user.id).any?
  end

  def borrow(user)
    unless available?
      errors.add(:base, 'Not available')
      return false
    end

    if already_borrowed_by_this_user?(user)
      errors.add(:base, 'Already borrowed by this user')
      return false
    end

    borrowed = borroweds.new(borrowed_at: Date.current, user_id: user.id)
    return borrowed if borrowed.save

    errors.add(:base, 'Unexpected Error')
    false
  end
end

# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string
#  isbn       :string
#  synopsis   :string
#  copies     :integer
#  language   :string
#  pages      :integer
#  series     :string
#  volume     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/book/detail.rb
# frozen_string_literal: true

class Book::Detail < ApplicationRecord
  belongs_to :book

  validates_presence_of :name, :description

  enum name: {
    author: 1,
    genre: 2,
    publisher: 3
  }
end

# == Schema Information
#
# Table name: book_details
#
#  id          :integer          not null, primary key
#  name        :integer
#  description :string
#  book_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_book_details_on_book_id  (book_id)
#

app/controllers/api/v1/book/details_controller.rb
# frozen_string_literal: true

class Api::V1::Book::DetailsController < Api::V1::ApplicationController
  before_action :set_book
  before_action :set_detail, only: %i[show update destroy]

  # GET /api/v1/books/1 or /api/v1/books/1.json
  def show; end

  # POST /books/1/details or /books/1/details.json
  def create
    @detail = @book.details.new(detail_params)

    render json: @detail.errors, status: :unprocessable_entity unless @detail.save
  end

  def update
    if @detail.update(detail_params)
      render :show, status: :ok, location: @detail
    else
      render json: @detail.errors, status: :unprocessable_entity
    end
  end

  # DELETE /books/1/details/1 or /books/1/details/1.json
  def destroy
    if @detail.destroy
      head :no_content
    else
      render json: @detail.errors, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_detail
    @detail = @book.details.find(params[:id])
    authorize @detail
  end

  def set_book
    @book = Book.find(params[:book_id])
  end

  # Only allow a list of trusted parameters through.
  def detail_params
    params.require(:detail).permit(:name, :description)
  end

  def allow_sort
    %w[name description].include?(params[:sort_by].to_s)
  end

  def sort_details
    return unless allow_sort

    sort_order = params[:sort_order] == 'DESC' ? 'DESC' : 'ASC'
    sort = { params[:sort_by].to_sym => sort_order }

    @details = @details.order(sort)
  end
end

app/controllers/api/v1/books_controller.rb
# frozen_string_literal: true

class Api::V1::BooksController < Api::V1::ApplicationController
  before_action :set_book, only: %i[show update destroy borrow]

  ALLOWED_SORTS = %w[id title isbn].freeze

  # GET /books or /books.json
  def index
    authorize Book

    @books = sort(Book, ALLOWED_SORTS)
    @pagy, @books = pagy(@books)
    @pagination = pagy_metadata(@pagy)
  end

  def search
    authorize Book
    @books = sort(Book.search(params[:query]), ALLOWED_SORTS)
    @pagy, @books = pagy(@books)
    @pagination = pagy_metadata(@pagy)
    render :index
  end

  # GET /api/v1/books/1 or /api/v1/books/1.json
  def show; end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    authorize @book
    if @book.save
      if details_params.present?
        details_params[:details].each do |detail|
          @book.details.create(name: detail['name'], description: detail['description'])
        end
      end
      render :show, status: :created, location: @book
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def update
    if @book.update(book_params)
      render :show, status: :ok, location: @book
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  # DELETE /api/v1/books/1 or /api/v1/books/1.json
  def destroy
    if @book.destroy
      head :no_content
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def borrow
    user = current_user.librarian? && users_params.present? && users_params[:id].present? ? User.find(users_params[:id]) : current_user
    borrowed = @book.borrow(user)
    if borrowed
      render json: { expected_return: borrowed.expected_return, borrowed_id: borrowed.id }, status: :ok
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:book_id] || params[:id])
    authorize @book
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :isbn, :synopsis, :copies, :language, :pages, :series, :volume)
  end

  def details_params
    params.require(:book).permit(details: %i[name description])
  end

  def users_params
    params.require(:user).permit(:id) if params[:user].present?
  end
end

app/controllers/book/details_controller.rb
# frozen_string_literal: true

class Book::DetailsController < ApplicationController
  before_action :set_book
  before_action :set_detail, only: %i[show edit update destroy]

  ALLOWED_SORTS = %w[id name description].freeze

  # GET /books/1/details or /books/1/details.json
  def index
    authorize Book::Detail

    @details = sort(@book.details, ALLOWED_SORTS)

    render(partial: 'book/details/table', locals: { details: @details })
  end

  # GET /books/1/books/1/detailsnew
  def new
    authorize Book::Detail
    @detail = @book.details.new
  end

  # POST /books/1/details or /books/1/details.json
  def create
    @detail = @book.details.new(detail_params)

    if @detail.save
      flash[:success] = 'Detail was successfully created.'
      redirect_to book_url(@detail.book)
    else
      flash[:error] = 'Detail not created'
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @detail.update(detail_params)
      flash[:success] = 'Detail was successfully updated.'
      redirect_to book_url(@detail.book.id)
    else
      flash[:error] = 'Detail not updated'
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /books/1/books/1/details1 or /books/1/books/1/details1.json
  def destroy
    if @detail.destroy
      flash[:success] = 'Detail was successfully destroyed.'
    else
      flash[:error] = 'Detail not deleted'
    end
    redirect_to details_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_detail
    @detail = @book.details.find(params[:id])
    authorize @detail
  end

  def set_book
    @book = Book.find(params[:book_id])
  end

  # Only allow a list of trusted parameters through.
  def detail_params
    params.require(:book_detail).permit(:name, :description)
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_books, only: %i[index list]
  before_action :set_book, only: %i[show edit update destroy borrow]

  ALLOWED_SORTS = %w[id title isbn].freeze

  # GET /books or /books.json
  def index; end

  def list
    render(partial: 'books/table', locals: { books: @books })
  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/new
  def new
    authorize Book
    @book = Book.new
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:success] = 'Book was successfully created.'
      redirect_to book_url(@book)
    else
      flash[:error] = 'Book not created'
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @book.update(book_params)
      flash[:success] = 'Book was successfully updated.'
      redirect_to book_url(@book)
    else
      flash[:error] = 'Book not updated'
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    if @book.destroy
      flash[:success] = 'Book was successfully destroyed.'
    else
      flash[:error] = 'Book not deleted'
    end
    redirect_to books_url
  end

  def borrow
    user = current_user.librarian? ? User.find(params[:user_id]) : current_user
    borrowed = @book.borrow(user)
    if borrowed
      flash[:success] = 'Book was successfully borrowed.'
    else
      flash[:error] = 'Book was not borrowed'
    end

    redirect_to book_url(@book)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:book_id] || params[:id])
    authorize @book
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :isbn, :synopsis, :copies, :language, :pages, :series, :volume)
  end

  def set_books
    authorize Book

    @books = Book.search(params[:query])
    @books = sort(@books, ALLOWED_SORTS)
    @pagy, @books = pagy(@books)
  end
end

app/helpers/book_helper.rb
# frozen_string_literal: true

module BookHelper
end

app/views/book/details/_form.html.erb
<%= form_with(model: detail, url: book_detail_path(detail.book, detail)) do |form| %>
  <div class="row">
    <div class="col-12">
      <% if detail.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

          <ul>
            <% detail.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6 mb-1">
      <div class="form-floating">
        <%= form.select :name, Book::DetailPresenter.name_options, {}, class: "form-select", disabled: readonly %>
        <%= form.label :name %>
      </div>
    </div>
    <div class="col-sm-12 col-md-6 mb-1">
      <div class="form-floating">
        <%= form.text_field :description, class: "form-control", readonly: readonly %>
        <%= form.label :description %>
      </div>
    </div>
  </div>
  <% unless readonly %>
    <div class="row">
      <div class="col-12">
        <%= form.submit 'Save', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/book/details/_table.html.erb
<%= turbo_frame_tag "books_table" do %>
  <div class="row">
    <div class="col-12 table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">
              <%= sort_link(column: :id, label: '#', link: book_details_path(@book)) %>
            </th>
            <th scope="col">
              <%= sort_link(column: :name, label: 'Name', link: book_details_path(@book)) %>
            </th>
            <th scope="col">
              <%= sort_link(column: :description, label: 'Description', link: book_details_path(@book)) %>
            </th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% details.each do |detail| %>
            <tr>
              <td><%= detail.id %></td>
              <td><%= detail.name %></td>
              <td><%= detail.description %></td>
              <td>
                <div class="btn-group me-2">
                  <% if current_user.librarian? %>
                    <%= link_to book_detail_path(detail.book, detail), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" do %>
                      <i class="bi bi-trash"></i>
                    <% end %>
                    <%= link_to edit_book_detail_path(detail.book, detail), class: "btn btn-sm btn-outline-primary", data: { turbo: false } do %>
                      <i class="bi bi-pencil-square"></i>
                    <% end %>
                  <% end%>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/book/details/edit.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row mb-1">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 border-bottom">
        <h1 class="h2">Editing <%= @detail.description %></h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <div class="btn-group me-2">
            <%= link_to book_path(@detail.book), class: "btn btn-sm btn-outline-secondary" do %>
              <i class="bi bi-arrow-return-left"></i> Back to Book
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render "form", detail: @detail, readonly: false %>
</div>

app/views/book/details/new.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row mb-1">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 border-bottom">
        <h1 class="h2">New detail</h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <%= link_to book_path(@detail.book), class: "btn btn-sm btn-outline-secondary" do %>
            <i class="bi bi-arrow-return-left"></i> Back to Book
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= render "form", detail: @detail, readonly: false %>
</div>